/** Label keys used in invitation UI - for admin editing and translation lookup */
export const LABEL_KEYS = [
  "dearPrefix",
  "to",
  "dearGuest",
  "tapSealToOpen",
  "saveTheDate",
  "venue",
  "gallery",
  "wishes",
  "visibleToAllGuests",
  "rsvp",
  "rsvpDefaultMessage",
  "pleaseRespondBy",
  "attending",
  "notAttending",
  "addToCalendar",
  "refresh",
  "call",
  "music",
  "map",
  "maps",
  "waze",
] as const
